services:
  redis-standalone-1:
    image: redis/redis-stack-server:7.4.0-v1
    ports:
      - "7001:6379"
    volumes:
      - ./config/redis/standalone.conf:/redis-stack.conf
      - ./data/redis/7001:/data
    env_file:
      - ./config/redis/docker.env
  redis-standalone-2:
    image: redis/redis-stack-server:7.4.0-v1
    ports:
      - "7002:6379"
    volumes:
      - ./config/redis/standalone.conf:/redis-stack.conf
      - ./data/redis/7002:/data
    env_file:
      - ./config/redis/docker.env
  redis-node-01:
    image: redis/redis-stack-server:7.4.0-v1
    command: [ "bash", "/home/runner/mounted/node.sh", "7101" ]
    network_mode: "host"
    volumes:
      - ./config/redis:/home/runner/mounted
      - ./data/redis/7101:/data
    env_file:
      - ./config/redis/docker.env
  redis-node-02:
    image: redis/redis-stack-server:7.4.0-v1
    command: [ "bash", "/home/runner/mounted/node.sh", "7102" ]
    network_mode: "host"
    volumes:
      - ./config/redis:/home/runner/mounted
      - ./data/redis/7102:/data
    env_file:
      - ./config/redis/docker.env
  redis-node-03:
    image: redis/redis-stack-server:7.4.0-v1
    command: [ "bash", "/home/runner/mounted/node.sh", "7103" ]
    network_mode: "host"
    volumes:
      - ./config/redis:/home/runner/mounted
      - ./data/redis/7103:/data
    env_file:
      - ./config/redis/docker.env
  redis-node-04:
    image: redis/redis-stack-server:7.4.0-v1
    command: [ "bash", "/home/runner/mounted/node.sh", "7104" ]
    network_mode: "host"
    volumes:
      - ./config/redis:/home/runner/mounted
      - ./data/redis/7104:/data
    env_file:
      - ./config/redis/docker.env
  redis-cluster-creator:
    image: redis/redis-stack-server:7.4.0-v1
    command: redis-cli -a "$REDIS_PASSWORD" --cluster create $REDIS_PUBLIC_IP:7101 $REDIS_PUBLIC_IP:7102 $REDIS_PUBLIC_IP:7103 $REDIS_PUBLIC_IP:7104 --cluster-replicas 0 --cluster-yes
    network_mode: "host"
    depends_on:
      - redis-node-01
      - redis-node-02
      - redis-node-03
      - redis-node-04
    env_file:
      - ./config/redis/docker.env

  mariadb:
    image: mariadb:10.11.5
    environment:
      - MARIADB_DATABASE=dashboard-globalping
      - MARIADB_USER=directus
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - "13306:3306"
    volumes:
      - ./config/create-dbs.sql:/docker-entrypoint-initdb.d/01-create-dbs.sql
      - ./migrations/create-tables.js.sql:/docker-entrypoint-initdb.d/02-create-tables.sql
