services:
  redis-standalone-1:
    image: redis/redis-stack-server:7.4.0-v1
    ports:
      - "7001:7001"
    volumes:
      - ./config/redis/standalone-1.conf:/redis-stack.conf
      - ./data/redis/7001:/data
    env_file:
      - ./config/redis/.env.redis
  redis-standalone-2:
    image: redis/redis-stack-server:7.4.0-v1
    ports:
      - "7002:7002"
    volumes:
      - ./config/redis/standalone-2.conf:/redis-stack.conf
      - ./data/redis/7002:/data
    env_file:
      - ./config/redis/.env.redis
  redis-standalone-3:
    image: redis/redis-stack-server:7.4.0-v1
    ports:
      - "7003:7003"
    volumes:
      - ./config/redis/standalone-3.conf:/redis-stack.conf
      - ./data/redis/7003:/data
    env_file:
      - ./config/redis/.env.redis
  redis-node-01:
    image: redis/redis-stack-server:7.4.0-v1
    command: [ "bash", "/home/runner/mounted/node.sh", "7101" ]
    network_mode: "host"
    volumes:
      - ./config/redis:/home/runner/mounted
      - ./data/redis/7101:/data
    env_file:
      - ./config/redis/.env.redis
  redis-node-02:
    image: redis/redis-stack-server:7.4.0-v1
    command: [ "bash", "/home/runner/mounted/node.sh", "7102" ]
    network_mode: "host"
    volumes:
      - ./config/redis:/home/runner/mounted
      - ./data/redis/7102:/data
    env_file:
      - ./config/redis/.env.redis
  redis-node-03:
    image: redis/redis-stack-server:7.4.0-v1
    command: [ "bash", "/home/runner/mounted/node.sh", "7103" ]
    network_mode: "host"
    volumes:
      - ./config/redis:/home/runner/mounted
      - ./data/redis/7103:/data
    env_file:
      - ./config/redis/.env.redis
  redis-node-04:
    image: redis/redis-stack-server:7.4.0-v1
    command: [ "bash", "/home/runner/mounted/node.sh", "7104" ]
    network_mode: "host"
    volumes:
      - ./config/redis:/home/runner/mounted
      - ./data/redis/7104:/data
    env_file:
      - ./config/redis/.env.redis
  redis-cluster-creator:
    image: redis/redis-stack-server:7.4.0-v1
    command: bash -c 'redis-cli -a "$$REDIS_PASSWORD" --cluster create $$REDIS_PUBLIC_IP:7101 $$REDIS_PUBLIC_IP:7102 $$REDIS_PUBLIC_IP:7103 $$REDIS_PUBLIC_IP:7104 --cluster-replicas 0 --cluster-yes'
    network_mode: "host"
    depends_on:
      - redis-node-01
      - redis-node-02
      - redis-node-03
      - redis-node-04
    env_file:
      - ./config/redis/.env.redis

  mariadb:
    image: mariadb:10.11.5
    environment:
      - MARIADB_DATABASE=dashboard-globalping
      - MARIADB_USER=directus
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - "13306:3306"
    volumes:
      - ./config/dashboard/create-dbs.sql:/docker-entrypoint-initdb.d/01-create-dbs.sql
      - ./migrations/dashboard/create-tables.js.sql:/docker-entrypoint-initdb.d/02-create-tables.sql

  measurement-store-1:
    image: timescale/timescaledb:2.24.0-pg18
    environment:
      - POSTGRES_USER=globalping-api
      - POSTGRES_PASSWORD=password
    ports:
      - "15432:5432"
    volumes:
      - ./config/measurement-store-1/create-dbs.sql:/docker-entrypoint-initdb.d/01-create-dbs.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d postgres -h 127.0.0.1"]
      interval: 3s
      timeout: 3s
      retries: 20

  measurement-store-1-migrator:
    image: node:22-alpine
    working_dir: /app
    depends_on:
      measurement-store-1:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - NODE_CONFIG={"measurementStoreDb":{"connection":{"host":"measurement-store-1","port":5432}}}
    volumes:
      - ./:/app
    command: sh -c "npm run knex:measurement-store-1 migrate:latest"

  time-series-1:
    image: timescale/timescaledb:2.24.0-pg18
    environment:
      - POSTGRES_USER=globalping-api
      - POSTGRES_PASSWORD=password
    ports:
      - "15442:5432"
    volumes:
      - ./config/time-series-1/create-dbs.sql:/docker-entrypoint-initdb.d/01-create-dbs.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d postgres -h 127.0.0.1"]
      interval: 3s
      timeout: 3s
      retries: 20

  time-series-1-migrator:
    image: node:22-alpine
    working_dir: /app
    depends_on:
      time-series-1:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - NODE_CONFIG={"timeSeriesDb":{"connection":{"host":"time-series-1","port":5432}}}
    volumes:
      - ./:/app
    command: sh -c "npm run knex:time-series-1 migrate:latest"
