name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: Run e2e tests
    runs-on: ubicloud-standard-4

    env:
      NODE_ENV: test

    services:
      mariadb:
        image: mariadb:10.11.5
        ports:
          - 13306:3306
        env:
          MARIADB_DATABASE: dashboard-globalping-test
          MARIADB_USER: directus
          MARIADB_PASSWORD: password
          MARIADB_RANDOM_ROOT_PASSWORD: 1
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: ubicloud/setup-node@v4
        with:
          node-version: 20.x
      - name: Enable IPv6 for Docker containers
        run: |
          sudo cat /etc/docker/daemon.json | jq '. + { "ipv6": true, "fixed-cidr-v6": "2001:db8:1::/64", "experimental": true, "ip6tables": true }' > daemon.json
          sudo mv daemon.json /etc/docker/
          sudo systemctl restart docker
          docker restart $(docker ps -aq)
      - name: Set up Redis
        run: |
          cp config/redis/.env.redis ./
          docker compose --env-file .env.redis up -d
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Test E2E
        run: |
          npm run test:e2e
